# Generated by Django 6.0.5 on 2026-05-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratelimitentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ratelimitentry',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, unique=True),
        ),
    ]
