# Generated by Django 6.0.5 on 2026-05-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_ratelimitentry_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateLimitEntry',
        ),
    ]
